# Generated by Django 4.1 on 2023-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_sub_div'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('room_num', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('orientation', models.CharField(max_length=200)),
                ('h_num', models.CharField(max_length=200)),
                ('s_num', models.CharField(max_length=200)),
                ('agent_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sub_div',
            name='div_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
