# Generated by Django 4.1 on 2023-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rename_new_div_id_sub_div_div_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_div_old',
            name='surr_business',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='sub_div_old',
            name='surr_entertain',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='sub_div_old',
            name='surr_school',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='sub_div_old',
            name='surr_trafic',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
