# Generated by Django 4.1 on 2023-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_new_s_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_div_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_url', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('build_year', models.IntegerField()),
                ('house_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('div_id', models.CharField(max_length=200)),
                ('property_company', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('property_fee', models.CharField(max_length=200)),
                ('house_type', models.CharField(max_length=200)),
                ('surr_envi', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='listing_new',
            name='s_num',
            field=models.CharField(max_length=200),
        ),
    ]
