# Generated by Django 4.1 on 2023-04-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_div_id_sub_div_new_div_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_div',
            old_name='new_div_id',
            new_name='div_id',
        ),
    ]
